### PR TITLE
Fixes for #240

### PR DESCRIPTION
**Pull request by jollyroger**
These changes target all issues mentioned in bug #240.

### CODE REVIEW

**Comment by pah** [comment]
Somehow the AppVeyor build has still failed even with your changes. I don't see the changes from 2e79af6 reflected in the [build log] [1]. 

@Kosta-Github: Is the AppVeyor environment cached between runs? Do we need to "clean" the build tree before running? 

[1]: https://ci.appveyor.com/project/miloyip/rapidjson/build/0.12.5/job/2c26ped4qvq8x3kx

**Comment by Kosta-Github** [comment]
AppVeyor is doing a clean build each time it runs ( just like Travis). 

I think the camke definition needs to be -D instead of /D ...

**Comment by Kosta-Github** [comment]
-D is also missing on 2 or 3 other cmake config files (e.g., for the examples)...

**Comment by Kosta-Github** [comment]
The VS2012 compiler does not adhere to the standard with respect to `nothrow` support; some of the `static_asserts` in this file https://github.com/miloyip/rapidjson/blame/master/test/unittest/stringbuffertest.cpp#L86 need to be either disabled for `_MSC_VER` (all VS compiler versions) or selectively for VS2012 (preferred solution)...

**Pull request merged**
