### PR TITLE
Build with 2 threads

### PR DESCRIPTION
**Pull request by thedrow**
This should make the build a bit faster since we have 2 cores on each build VM.
I'm not sure about running the tests in parallel since some of them are performance tests.
What do you think?

### CODE REVIEW

**Comment by thedrow** [comment]
22 minutes instead of 24. Much better.

**Comment by thedrow** [comment]
@miloyip Should the preftests report correct results that can be used for performance evaluation on Travis or are they run just to prove that they work?

**Comment by miloyip** [comment]
I think there is no guarantee on what spec of build machine it will be running, nor number of simultaneous builds that will be running at the same time. So that the results of perftest is not very useful. It merely runs for showing the perftest itself is runnable, without runtime errors.

**Comment by thedrow** [comment]
@miloyip Good to know. The changeset is include in #504 so I'm gonna close this.

**Pull request closed without merging**
