### PR TITLE
Adding coapp definition

### PR DESCRIPTION
**Pull request by stunney**
To create a nupkg, call CoApp's Write-NuGetPackage .\rapidjson.autopkg
-defines:MYVERSION=1.0.2 (or whatever version you want to call it)

### CODE REVIEW

**Comment by miloyip** [comment]
Will it be better using https://github.com/miloyip/rapidjson/blob/master/license.txt as licenseUrl?

**Comment by stunney** [comment]
Yes, yes it would. :)

Sent from Yahoo Mail on Android

**Comment by Kosta-Github** [comment]
Maybe you can add the sample commandline invokation as a comment to the package def file as well?

**Comment by stunney** [comment]
@Kosta-Github  you mean as a comment at the top of the .autopkg file?

**Comment by stunney** [comment]
@Kosta-Github I have added comments to the top of the .autopkg file

**Pull request merged**
