### PR TITLE
Deb packaging with CPack

### PR DESCRIPTION
**Pull request by vitalyisaev2**
Hello! First we would like to thank you for a nice library. Some of our Ubuntu-based solutions rely on Rapidjson, so we would like to make the use of it a bit more standardized. At the moment our projects acquire Rapidjson as a git submodule, but it's not very convenient due to the absence of of version control which is prefferable for our build system. That's why we would like to have packages.

This patch provides the opportunity for building binary deb packages with **CPack** tool (full-featured debianization seem to be overkill for this case). Everything is based on your actual ```CMakeLists.txt```.  So far we got two packages (according to the ```components``` specified in ```CMakeLists.txt```):

1. rapidjson-dev
2. rapidjson-examples 

```bash
root@9497495eef1e:~/rapidjson# cmake .
root@9497495eef1e:~/rapidjson# cpack
CPack: Create package using TGZ
CPack: Install projects
CPack: - Run preinstall target for: RapidJSON
CPack: - Install project: RapidJSON
CPack: Create package
CPack: - package: /root/rapidjson/rapidjson_0.12.0~git20151704-1_all.tar.gz generated.
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: RapidJSON
CPack: - Install project: RapidJSON
CPack: -   Install component: dev
CPack: -   Install component: examples
CPack: Create package
CPack: - package: /root/rapidjson/rapidjson_0.12.0~git20151704-1_all-dev.deb generated.
CPack: - package: /root/rapidjson/rapidjson_0.12.0~git20151704-1_all-examples.deb generated.
```

You may check the content of packages:
```bash
root@9497495eef1e:~/rapidjson# dpkg -c rapidjson_0.12.0~git20151704-1_all-dev.deb
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/include/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/include/rapidjson/
-rw-r--r-- root/root      2563 2015-04-17 11:55 ./usr/local/include/rapidjson/memorybuffer.h
-rw-r--r-- root/root      2882 2015-04-17 11:55 ./usr/local/include/rapidjson/filewritestream.h
-rw-r--r-- root/root     59281 2015-04-17 11:55 ./usr/local/include/rapidjson/reader.h
-rw-r--r-- root/root     14133 2015-04-17 11:55 ./usr/local/include/rapidjson/writer.h
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/include/rapidjson/error/
-rw-r--r-- root/root      3677 2015-04-17 11:55 ./usr/local/include/rapidjson/error/en.h
-rw-r--r-- root/root      5677 2015-04-17 11:55 ./usr/local/include/rapidjson/error/error.h
-rw-r--r-- root/root      3167 2015-04-17 11:55 ./usr/local/include/rapidjson/stringbuffer.h
-rw-r--r-- root/root      9903 2015-04-17 11:55 ./usr/local/include/rapidjson/encodedstream.h
-rw-r--r-- root/root      2471 2015-04-17 11:55 ./usr/local/include/rapidjson/memorystream.h
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/include/rapidjson/msinttypes/
-rw-r--r-- root/root      8372 2015-04-17 11:55 ./usr/local/include/rapidjson/msinttypes/inttypes.h
-rw-r--r-- root/root      9327 2015-04-17 11:55 ./usr/local/include/rapidjson/msinttypes/stdint.h
-rw-r--r-- root/root      9993 2015-04-17 11:55 ./usr/local/include/rapidjson/allocators.h
-rw-r--r-- root/root     23547 2015-04-17 11:55 ./usr/local/include/rapidjson/encodings.h
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/include/rapidjson/internal/
-rw-r--r-- root/root      3621 2015-04-17 11:55 ./usr/local/include/rapidjson/internal/pow10.h
-rw-r--r-- root/root      8134 2015-04-17 11:55 ./usr/local/include/rapidjson/internal/strtod.h
-rw-r--r-- root/root     10306 2015-04-17 11:55 ./usr/local/include/rapidjson/internal/itoa.h
-rw-r--r-- root/root      6781 2015-04-17 11:55 ./usr/local/include/rapidjson/internal/dtoa.h
-rw-r--r-- root/root     11227 2015-04-17 11:55 ./usr/local/include/rapidjson/internal/diyfp.h
-rw-r--r-- root/root      1419 2015-04-17 11:55 ./usr/local/include/rapidjson/internal/strfunc.h
-rw-r--r-- root/root      6841 2015-04-17 11:55 ./usr/local/include/rapidjson/internal/meta.h
-rw-r--r-- root/root      8833 2015-04-17 11:55 ./usr/local/include/rapidjson/internal/biginteger.h
-rw-r--r-- root/root      5766 2015-04-17 11:55 ./usr/local/include/rapidjson/internal/stack.h
-rw-r--r-- root/root      2886 2015-04-17 11:55 ./usr/local/include/rapidjson/internal/ieee754.h
-rw-r--r-- root/root     21431 2015-04-17 11:55 ./usr/local/include/rapidjson/rapidjson.h
-rw-r--r-- root/root      7926 2015-04-17 11:55 ./usr/local/include/rapidjson/prettywriter.h
-rw-r--r-- root/root      2889 2015-04-17 11:55 ./usr/local/include/rapidjson/filereadstream.h
-rw-r--r-- root/root     85502 2015-04-17 11:55 ./usr/local/include/rapidjson/document.h
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/lib/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/lib/cmake/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/lib/cmake/RapidJSON/
-rw-r--r-- root/root       455 2015-04-17 12:00 ./usr/local/lib/cmake/RapidJSON/RapidJSONConfigVersion.cmake
-rw-r--r-- root/root       197 2015-04-17 12:00 ./usr/local/lib/cmake/RapidJSON/RapidJSONConfig.cmake
root@9497495eef1e:~/rapidjson# dpkg -c rapidjson_0.12.0~git20151704-1_all-examples.deb
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/capitalize/
-rw-r--r-- root/root      2436 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/capitalize/capitalize.cpp
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/prettyauto/
-rw-r--r-- root/root      2288 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/prettyauto/prettyauto.cpp
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/messagereader/
-rw-r--r-- root/root      2686 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/messagereader/messagereader.cpp
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/pretty/
-rw-r--r-- root/root      1036 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/pretty/pretty.cpp
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/simplereader/
-rw-r--r-- root/root      1678 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/simplereader/simplereader.cpp
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/simpledom/
-rw-r--r-- root/root       685 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/simpledom/simpledom.cpp
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/tutorial/
-rw-r--r-- root/root      6407 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/tutorial/tutorial.cpp
-rw-r--r-- root/root       875 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/CMakeLists.txt
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/condense/
-rw-r--r-- root/root      1034 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/condense/condense.cpp
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/simplewriter/
-rw-r--r-- root/root       738 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/simplewriter/simplewriter.cpp
drwxr-xr-x root/root         0 2015-04-17 12:15 ./usr/local/share/doc/RapidJSON/examples/serialize/
-rw-r--r-- root/root      4161 2015-04-17 11:55 ./usr/local/share/doc/RapidJSON/examples/serialize/serialize.cpp
```

### CODE REVIEW

**Comment by vitalyisaev2** [comment]
I see that Travis has been broken by this line:
```Cmake
    string(TIMESTAMP DATE "%Y%d%m")
```
I guess Travis can just be outdated. My  Cmake version is ```2.8.12.2-0ubuntu6```.

**Comment by miloyip** [comment]
Is it possible to fix this by:

1. Install a newer version of CMAKE in travis script
2. Check version of CMAKE in the CMakeLists.txt and prevent calling invalid function

I do not familiar with these packages. Will it be useful to pack license, documents (markdown and/or doxygen) output as well?

**Comment by vitalyisaev2** [comment]
@miloyip, thanks for a prompt reply. We can pack all the files generated during the ```make``` command execution, according to the list of components in your ```CMakeLists.txt```. We can do up to four packages: ```dev```, ```doc```, ```pkgconfig``` and ```examples``` (but I'm not sure if ```rapidjson-pkgconfig``` would make sense for users).

We can also include license file in packages if you wish.

I'll try to fix Travis in soon.

**Comment by shindo** [comment]
We had the same problem (using RapidJSON as git submodule, instead of packages), thus I'd like to ask some related questions here.

1. @miloyip, are you going to support these packages officially? E.g. to add them to debian sid.

 If yes, I'd like to see support for Lucid/Precise/Trusty (this is completely possible, but requires support for older GCC, CMake and Valgrind versions).
And what about other Linux distributions (like RHEL)?

 If you're not going to do this, I'd like to ask you to think it over before applying this patch.

2. @vitalyisaev2, what about versioned -dev package, like rapidjson\<API_VERSION\>-dev?

 This allows one to explicitly specify which API version of RapidJSON they want to compile with (in debian/control).
 You can read about this scheme here:
 - https://people.debian.org/~adeodato/tmp/2006-03-16/library-transitions.txt
 - https://www.netfort.gr.jp/~dancer/column/libpkg-guide/libpkg-guide.html#id291895

 I think that pkgconfig files (as well as cmake config files) should go with -dev package, and examples with -doc package.

3. @miloyip, I'd like to ask about your versioning scheme, because it relates to my second question.

 Is it right that you chose MAJOR.MINOR versioning scheme?
 This means that all RapidJSON 1.X versions will support 1.0 API and all changes that break API will go to 2.0.

Actually, I created separate repo for packaging RapidJSON (https://github.com/shindo/librapidjson), because I thought you would not support RapidJSON packages.

**Comment by vitalyisaev2** [comment]
There are several opportunities for project debianization:
1. Full-featured, "canonical" debianization (with ```./debian```, changelog file, etc.)
2. Simplified debianization with binary package generators like **CMake/CPack** (no changelog needed). 

@miloyip You should choose the first option in case if you (as a project owner) or someone else are ready to maintain the package. This is a nice and canonical way of working with debian packages. I would be happy if this project has found its maintainer. But if you are not ready to spend extra time, you can allow your users (like me) just to build binary packages from upstream.

@shindo I approve the version notation that you suggested. But since the version hasn't been changed for a long time, I decided to add date string to the package name. With this patch you'll get the packages with a following names:
- rapidjson_0.12.0~git20151704-1_all-dev.deb
- rapidjson_0.12.0~git20151704-1_all-doc.deb
- rapidjson_0.12.0~git20151704-1_all-examples.deb

Actually someone from Debian attempted to do the same thing half a year ago: 
https://launchpad.net/ubuntu/vivid/+package/rapidjson-dev

**Comment by shindo** [comment]
@vitalyisaev2, from my point of view this simplified debianization is a half solution, that's why I asked @miloyip to think it over if packaging will not be supported officially.
Because if this patch will be applied, proposed solution will be "official way" to package RapidJSON (with its package versioning/naming), thus this debianization must be suitable for most users.

**Comment by miloyip** [comment]
Firstly, I need to admit that I am not familiar with Linux distributions. I would like to seek assistance on these issues and advices form the community. I think I will not directly maintain the packages. Is it possible to authorise community volunteers to help on this issue?

@shindo 

> If yes, I'd like to see support for Lucid/Precise/Trusty (this is completely possible, but requires support for older GCC, CMake and Valgrind versions).

I would like to see that happens. Actually RapidJSON was designed for C++03 and optional C++11 support. I try to make it support older compilers. CMake and Valgrind are actually only for testing and building tests/examples, I do not think that are really important factors. Regarding to older compilers, I can try to fix them, or accepting pull requests, but I may not able to test them for some platforms combinations.

> Is it right that you chose MAJOR.MINOR versioning scheme?
> This means that all RapidJSON 1.X versions will support 1.0 API and all changes that break API will go to 2.0.

Yes. This is what I am thinking of. But if the API do cause issues (bug or something), the API will still be changed in order to fix them.

@vitalyisaev2 

> debianization

I think keeping a changelog is a good thing anyway. I think after v1.0 beta, we shall maintain a good changelog.

> But since the version hasn't been changed for a long time, I decided to add date string to the package name. 

Yes, there was been a long time not updating the version. But recently we put quite a lot of efforts to push a official v1.0 release. And we will continue to improve the library with new features in coming versions. So, I don't think it is needed to add date for versioning purpose.

**Comment by vitalyisaev2** [comment]
@miloyip I am glad to hear that official debianization is coming. It's a nice feature. @shindo can you please consider merging your work into upstream?

**Comment by miloyip** [comment]
Do we need to resolve this issue before v1.0?

**Comment by pah** [comment]
@miloyip: As there is a RapidJSON package available in [Debian][1] (and Ubuntu as a result) already, I would suggest to release 1.0 first and then send a patch to the Debian maintainer (as I did for the [current version][2]).

The move to Cmake and the updated copyright are the most important packaging changes. I can try to push my `debian` branch with later this week.

[1]: http://packages.debian.org/rapidjson
[2]: http://metadata.ftp-master.debian.org/changelogs//main/r/rapidjson/rapidjson_0.12~git20141031-1_changelog

**Comment by jollyroger** [comment]
First, Debian Maintainers(DM) won't use your debianization directly. Chances they will look and analyze your ways of building the packages, but final decision will be after the Debian Maintainer.

Second, DMs work mostly with tarballs (if they are available). I'm not sure about the opinion of current DM on this point, but since there's a note on anonscm.debian.org in `debian/control` commented out, tarball is used as a source for building rapidjson packages. I'm almost sure that DM will use `git-buildpackage` to build `*.dsc` and `*.deb` and will keep all the packaging work in a separate branch (obviously, called `debian`). You may do the same and collaborate with the DM. However, when it comes to support of multiple versions/distributions, the number of support branches will keep growing as well (unless the package can be rebuilt without any modifications that is quite possible for RapidJSON).

Third, packages are not updated frequently inside Debian/Ubuntu after distribution release. Updated packages are distributed via debian-updates and are accepted on an individual basis. So, if you want to provide every supported distribution with a fresh `*.deb` packages, you should set up your PPA.

As for building packages with CPack, this tool almost always give bad results in more or less complex software. It's not hard to debianize the package though. With cmake build process properly set up the main file `debian/control` will shrink to just:

    %:
        dh $@

The other files in `debian/` won't change much since previous releases.

If you need any assistance on the Debian side, I'll gladly help you.

**Comment by shindo** [comment]
@jollyroger, what do you think about versioned -dev packages?

This technique is rarely used, but I see it as very helpful.
If one want to use API v1.0 of RapidJSON when there's v2.0 already, the following should be in debian/control:
```
Build-Depends: librapidjson-dev (>= 1.0), librapidjson-dev (<< 2.0)
```

But apt doesn't handle such kind of relations (<<), it will just fail because possible candidate version of RapidJSON (eg. 2.0) doesn't match the requirements.

**Comment by jollyroger** [comment]
@shindo, your example works fine for `Depends` header (see any python2 package, for example, . Why should it not work for `Build-Depends`?

    $ apt-cache show python-sqlparse|grep Depends
    Depends: python:any (>= 2.7.5-5~), python:any (<< 2.8)

As for versioned `-dev` packages, please give me more details and/or examples so I could understand you.

**Comment by vitalyisaev2** [comment]
@jollyroger @pah  

thank you for clarification, now I have enough reasons to withdraw my PR. Since there are plans to provide official debianization anytime soon, there is no need to use ```Cpack```

**Comment by jollyroger** [comment]
@shindo, I've read your previous messages regardion versioned packages. This approach was introduced at first to have a possibility to install multiple versions of the library on the host. At that time that number corresponded to the SONAME — version of the ABI, not API. In case of RapidJSON, there's no ABI since no compiled library is distributed. You should note that even in that case there was only one development package (e.g. there was multiple libjpeg* packages but a single libjpeg-dev).

I'd like you, and especially @miloyip to consider this: do you want your users to search headers in `/usr/include/rapidjson0/`, `/usr/include/rapidjson1`, `/usr/include/rapidjson2`, etc? How will you implement library search for CMake? 

I'll show you what does it mean for a release engineer (not me) to switch library for another API in such case:

 * fix all installation paths
 * fix library version
 * rename and fix all files related to build systems (in our case RapidJSONConfig.cmake.in, RapidJSONConfigVersion.cmake.in, RapidJSON.pc.in)

This is all mostly manual work to be done. I wonder how much will you forget to do and how much have I forgotten to mention in this list.

**Comment by shindo** [comment]
Yes, this version number is SONAME regarding binary libraries.

But with RapidJSON this is not the case. Here this number is API version. Thus I don't need to rewrite my code to work with any of RapidJSON packages of versions 1.* (still API can be extended, but supports API v1.0 and "behavoir" doesn't change).

As I see the main point on versioned -dev packages is (from https://www.netfort.gr.jp/~dancer/column/libpkg-guide/libpkg-guide.html#id291895):

> "Build-Depends: libfoo-dev" is not optimal

>The question is: Are you really sure all past/present/future version of that -DEV package can be used with the source to build the package? (i.e. is your API so fixed in stone that it will never have to be changed?) If this is not true, some trouble will happen every time the -DEV package changes.

Debian policy allows one to use >=, << relations (within Build-Depends and Depends), but how I know it will not try to find package of appropriate version, it will just fail if candidate version of the package doesn't match these relations.

Now there are two options with versioned -dev packages:
1. support multiple packages of different API versions (eg. librapidjson1-dev, librapidjson2-dev) with separate headers directories.
2. support only one such package. This can be done with `Provides` and `Conflicts` with the same virtual package.

The second option already allows one to specify API version they want to build with, eg.:
```
Build-Depends: librapidjson1-dev (>= 1.2.0)
```

The first option can be done by some magic within `FIND_PACKAGE(RapidJSON 1.2)` that will provide one with `${RAPIDJSON_INCLUDE_DIRS}` just like Boost does. I think this is possible but rather complex.
Binary libraries should support this as they're to be used at run time, while -dev packages are to be used at build time.

**Comment by pah** [comment]
@jollyroger You mentioned a RapidJSON repository on anonscm.debian.org? Do you have a pointer? I seem to miss some required Google-$foo to find it...

**Comment by jollyroger** [comment]
@pah not at all. I told that it was commented out (see link below)

http://codesearch.debian.net/results/anonscm%20package:rapidjson/page_0

**Comment by pah** [comment]
@jollyroger Ok, thanks for the clarification.

**Pull request closed without merging**
